spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10
    database: 0
    jedis.pool.max-active: 20
    jedis.pool.max-wait: -1
    jedis.pool.max-idle: 10
    jedis.pool.min-idle: 10
